### ISSUE TITLE
Making querysets lazy

### ISSUE THREAD

**Issue by EliotBerriot** [EliotBerriot/lifter#1]
This would lead to a serious performance improvements if querysets where lazily evaluated and all queries where combined in a single one before iterating on values.

This was first raised [on reddit](https://www.reddit.com/r/Python/comments/46bljc/a_lightweight_query_engine_for_python_iterables/d04ayjl):

> the idea is fun but the implementation looks bad. I supposed from a fast review that every time a filter asked, it is applied. It result with lots of copy and lots of iteration. 
>
> to avoid that every filters, sorting fields and limit or whatever should be store in the QuerySet and a method all() first() or aggregation method could optimize iterations and copy.

**Comment by EliotBerriot** [comment]
I think one way to achieve this is to follow django's implementation and internally use `Q` objects to represent query arguments. Each queryset could then be reduced to a list of Q objects, and when evaluation would be need, values would be populated using these objects as matchers, meaning we iterate only once.

**Comment by asfaltboy** [comment]
Nice! While using Q objects may seem like overkill, something like this would have the advantage of enabling "advanced queries" such as supporting advanced filters with operators like these

* _NOT_ - `~Q(foo=bar)`
* _OR_ - `Q(foo=baz) | Q(foo=bar)`

**Comment by EliotBerriot** [comment]
I agree it may seems overkill right now, but I also think we should not reinvent the wheel and reuse existing implementations (such as Django's) to solve this issue.

Handling complex OR/AND  queries as you described would definitely be great stuff!

**Comment by EliotBerriot** [comment]
I'started the work on this feature, the first part being using `Q`-like objects internally.

**Comment by EliotBerriot** [comment]
This was also fixed in #23
