### ISSUE TITLE
Setup a real documentation

### ISSUE THREAD

**Issue by EliotBerriot** [EliotBerriot/lifter#22]
The README is big enough, it's time to think about writing a real documentation (I'm for leaving a few exemple in the README, though, juste to give a taste of the package).

I've already some experience using Read The Docs, but if you have other suggestions, your input is welcome :)

**Comment by Ogreman** [comment]
Would prefer RTD over anything else :+1:

**Comment by EliotBerriot** [comment]
RTD it will be then ;)

**Comment by EliotBerriot** [comment]
Okay, a very basic documentation has been pushed to RTD: http://lifter.readthedocs.org

Contributions are welcome :)
