### ISSUE TITLE
Allow querying on field that do not exist on all models

### ISSUE THREAD

**Issue by EliotBerriot** [EliotBerriot/lifter#26]
Currently, if you query on a field that do not exist on all models, lifter will raise an error. Making this behaviour optional, would be an improvement. Example:

```python
manager.filter(User.optional_field.exists(), User.optional_field == 'value')
```

This was first raised on [reddit](https://www.reddit.com/r/django/comments/46bnf4/a_lightweight_query_engine_for_python_iterables/d0cc5pu)

**Comment by Permafacture** [comment]
+1

It would be good to have the opposite filter also, ie: `User.optional_field.does_no_exist()`.

I wonder if `optional_field is not None` (since people are used to dict.get returning None if the lookup fails) or `optional_field is Exists` would make sense.

**Comment by EliotBerriot** [comment]
I don't like the idea of created two methods, instead, you can use the `~` operator, that inverts a query (this work with any query ;).

Filter objects with the field:

```python
manager.filter(Model.optional_field.exists())
```

Filter objects without the field:

```python
manager.filter(~Model.optional_field.exists())
```
